apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-model-deployment
  labels:
    app: heart-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-model
  template:
    metadata:
      labels:
        app: heart-model
    spec:
      containers:
      - name: heart-model
        image: heart-model:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: heart-model-service
spec:
  type: NodePort # Use LoadBalancer if you are on AWS/GCP/Azure
  selector:
    app: heart-model
  ports:
    - protocol: TCP
      port: 80       # The port accessible outside the cluster
      targetPort: 5000 # The port your Flask/FastAPI app runs on inside the container